language: julia

os:
  - linux
  - osx

branches:
  only:
  - master
  
julia:
  - 0.6

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("NURBS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - cd $TRAVIS_BUILD_DIR && julia -e 'Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
